<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 ./penrose_triangle-large.glb -t
Author: Michael Ostroff (https://sketchfab.com/MichaelOstroff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/penrose-triangle-large-3e16e9c7432b4ac6b7d89eb1f3a2d321
Title: Penrose Triangle-Large
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_2: THREE.Mesh
    }
    materials: {
      ['Scene_-_Root']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/penrose_triangle-large.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials['Scene_-_Root']} rotation={[-0.3, 0, 0]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
